### ISSUE TITLE
bug: Cannot update resolved promise

### ISSUE THREAD

**Issue by umbri** [amphp/artax#105]
Random LogicException, on high load
```
PHP Fatal error:  Uncaught LogicException: Cannot update resolved promise in /home/vendor/amphp/amp/lib/Placeholder.php:52
Stack trace:
#0 /home/vendor/amphp/amp/lib/PrivatePromisor.php(54): Amp\PrivatePlaceholder->update(Array)
#1 /home/vendor/amphp/amp/lib/PrivatePromisor.php(77): Amp\PrivatePlaceholder->Amp\{closure}(Array)
#2 /home/vendor/amphp/artax/lib/Client.php(897): Amp\Deferred->update(Array)
#3 /home/vendor/amphp/amp/lib/Placeholder.php(58): Amp\Artax\Client->Amp\Artax\{closure}('one7,2','IQ','3...', NULL)
#4 /home/vendor/amphp/amp/lib/PrivatePromisor.php(54): Amp\PrivatePlaceholder->update('one7,2','IQ','3...')
#5 /home/vendor/amphp/amp/lib/PrivatePromisor.php(77): Amp\PrivatePlaceholder->Amp\{closure}('one7,2','IQ','3...')
#6 /home/vendor/amphp/artax/lib/BufferWriter.php(38): Amp\Deferred->update('one7,2','IQ','3...')
#7 /home/vendor/amphp/artax/ in /home/vendor/amphp/amp/lib/Placeholder.php on line 52
```

**Comment by kelunik** [comment]
We no longer support Artax v2, please upgrade to Artax v3.
