### ISSUE TITLE
bug: Promise already resolved

### ISSUE THREAD

**Issue by umbri** [amphp/artax#106]
```
PHP Fatal error:  Promise already resolved
Stack trace:
#0 /home/vendor/amphp/amp/lib/PrivatePromisor.php(50): Amp\PrivatePlaceholder->resolve(NULL, Object(Amp\Artax\Response))
#1 /home/vendor/amphp/amp/lib/PrivatePromisor.php(87): Amp\PrivatePlaceholder->Amp\{closure}(NULL, Object(Amp\Artax\Response))
#2 /home/vendor/amphp/artax/lib/Client.php(572): Amp\Deferred->succeed(Object(Amp\Artax\Response))
#3 /home/vendor/amphp/artax/lib/Client.php(485): Amp\Artax\Client->assignParsedResponse(Object(Amp\Artax\RequestCycle), Array)
#4 /home/vendor/amphp/artax/lib/Client.php(472): Amp\Artax\Client->parseSocketData(Object(Amp\Artax\RequestCycle))
#5 /home/vendor/amphp/artax/lib/Client.php(455): Amp\Artax\Client->consumeSocketData(Object(Amp\Artax\RequestCycle), 'HTTP/1.1 200 OK...')
#6 /home/vendor/amphp/artax/lib/Client.php(435): Amp\Artax\Client->onReadableSocket(Object(Amp\Artax\RequestCycle))
#7 /home/vendor/amphp/amp/lib/EvReactor.php(47): Amp\Artax\Client->Amp\Artax\{closure}('00000000173ff85...', Resource id #94431, NULL)
```

**Comment by kelunik** [comment]
Probable the same as #105.
