### ISSUE TITLE
[bug] amp_v2: Streams cannot emit values after calling resolve

### ISSUE THREAD

**Issue by umbri** [amphp/artax#109]
PHP Fatal error:  Uncaught Error: Streams cannot emit values after calling resolve in /home/vendor/amphp/amp/lib/Internal/Producer.php:51
Stack trace:
#0 /home/vendor/amphp/artax/lib/Client.php(373): Amp\Emitter->emit(Array)
#1 /home/vendor/amphp/artax/lib/Client.php(142): Amp\Artax\Client->onSocketResolve(Object(Amp\Artax\RequestCycle), NULL, Resource id #183128)
#2 /home/vendor/amphp/amp/lib/Internal/Placeholder.php(123): Amp\Artax\Client->Amp\Artax\{closure}(NULL, Resource id #183128)
#3 /home/vendor/amphp/artax/lib/HttpSocketPool.php(87): Amp\Deferred->resolve(Resource id #183128)
#4 /home/vendor/amphp/amp/lib/Internal/Placeholder.php(123): Amp\Artax\HttpSocketPool->Amp\Artax\{closure}(NULL, Resource id #183128)
#5 /home/vendor/amphp/artax/lib/SocketPool.php(142): Amp\Deferred->resolve(Resource id #183128)
#6 /home/vendor/amph in /home/vendor/amphp/amp/lib/Internal/Producer.php on line 51

**Comment by bwoebi** [comment]
Isn't this the same as #105 ?
