### ISSUE TITLE
Crypto negotiation failed

### ISSUE THREAD

**Issue by waleedmazhar** [amphp/artax#174]
codes used

```

$promises[$URI] = Amp\call(function () use ($client, $URI) {
                    // "yield" inside a coroutine awaits the resolution of the promise
                    // returned from Client::request(). The generator is then continued.
                    $response = yield $client->request($URI);

                    // Same for the body here. Yielding an Amp\ByteStream\Message
                    // buffers the entire message.
                    $body = yield $response->getStatus();

                    return $body;
                });

            $responses = Amp\Promise\wait(Amp\Promise\all($promises));

```
below is error output
```
Fatal error: Uncaught Amp\Socket\CryptoException: Crypto negotiation failed: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type in /var/www/html/vendor/amphp/socket/src/Internal/functions.php:118
Stack trace:
#0 /var/www/html/vendor/amphp/amp/lib/Loop/NativeDriver.php(172): Amp\Socket\Internal\{closure}('am', Resource id #293, Object(Amp\Deferred))
#1 /var/www/html/vendor/amphp/amp/lib/Loop/NativeDriver.php(68): Amp\Loop\NativeDriver->selectStreams(Array, Array, 4.782)
#2 /var/www/html/vendor/amphp/amp/lib/Loop/Driver.php(130): Amp\Loop\NativeDriver->dispatch(true)
#3 /var/www/html/vendor/amphp/amp/lib/Loop/Driver.php(70): Amp\Loop\Driver->tick()
#4 /var/www/html/vendor/amphp/amp/lib/Loop.php(76): Amp\Loop\Driver->run()
#5 /var/www/html/vendor/amphp/amp/lib/functions.php(158): Amp\Loop::run(Object(Closure))
#6 /var/www/html/parseradvance.php(77): Amp\Promise\wait(Object(Amp\Internal\PrivatePromise))
#7 {main}
  t in /var/www/html/vendor/amphp/socket/src/Internal/functions.php on line 118
```

**Comment by kelunik** [comment]
Could you share the URL you're trying to access?

**Comment by kelunik** [comment]
What does `var_dump(OPENSSL_VERSION_TEXT)` / `var_dump(OPENSSL_VERSION_NUMBER)` yield? Are you 100% sure that `https://www.yahoo.com/` is affected?

**Comment by bwoebi** [comment]
The DefaultClient constructor supports an \Amp\Socket\ClientTlsContext as third argument, on which you can set your own options like `withoutPeerVerification()`.

**Comment by waleedmazhar** [comment]
Thanks a lot! @kelunik @bwoebi

**Comment by kelunik** [comment]
@waleedmazhar Did it work with that?

**Comment by waleedmazhar** [comment]
yes

**Comment by kelunik** [comment]
Thanks, closing this issue then.
