### ISSUE TITLE
Unknown socket exception

### ISSUE THREAD

**Issue by Danack** [amphp/artax#71]
I'm getting the error below 'sometimes' - which is totally vague I know. It doesn't reproduce in simple code, but effectively all I'm doing is:

``` php
<?php

require_once "../vendor/autoload.php";

use Amp\Artax\Client as ArtaxClient;

$reactor = \Amp\getReactor();

$client1 = new ArtaxClient($reactor);
$client2 = new ArtaxClient($reactor);

$promise1 = $client1->request('http://www.google.com');
$response1 = \Amp\wait($promise1);

$promise2 = $client2->request('https://github.com/danack/imagick-demos/archive/1864936a93649bfd94cdad3b905b51eb6b416ac0.tar.gz');
$response2 = \Amp\wait($promise2);
```

As I said, that doesn't actually show the issue. 

```
Unexpected exception of type DomainException running Deployer`: Unknown socket: Resource id #186
#0 .../vendor/amphp/artax/lib/HttpSocketPool.php(114): Amp\Artax\SocketPool->checkin(Resource id #186)
#1 .../vendor/amphp/artax/lib/Client.php(543): Amp\Artax\HttpSocketPool->checkin(Resource id #186)
#2 .../vendor/amphp/artax/lib/Client.php(773): Amp\Artax\Client->assignParsedResponse(Object(Amp\Artax\RequestCycle), Array)
#3 .../vendor/amphp/artax/lib/Client.php(461): Amp\Artax\Client->processDeadSocket(Object(Amp\Artax\RequestCycle))
#4 .../vendor/amphp/artax/lib/Client.php(436): Amp\Artax\Client->onReadableSocket(Object(Amp\Artax\RequestCycle))
#5 .../vendor/amphp/amp/lib/NativeReactor.php(185): Amp\Artax\Client->Amp\Artax\{closure}(Object(Amp\NativeReactor), 25, Resource id #186)
#6 .../vendor/amphp/amp/lib/NativeReactor.php(151): Amp\NativeReactor->selectActionableStreams(98.0418)
#7 .../vendor/amphp/amp/lib/functions.php(534): Amp\NativeReactor->tick()
#8 .../src/.../Deployer/Deployer.php(103): Amp\wait(Object(Amp\Future))
#9 .../src/.../Deployer/Deployer.php(48): ...\Deployer\Deployer->downloadPackage('danack', 'imagick-demos', Object(GithubService\Model\Commit))
#10 [internal function]: ...\Deployer\Deployer->run()
#11 .../vendor/danack/auryn/lib/ReflectionMethodExecutable.php(27): ReflectionMethod->invokeArgs(Object(...\Deployer\Deployer), Array)
#12 [internal function]: Auryn\ReflectionMethodExecutable->__invoke()
#13 .../vendor/danack/auryn/lib/AurynInjector.php(125): call_user_func_array(Array, Array)
#14 .../vendor/danack/auryn/lib/AurynInjector.php(117): Auryn\AurynInjector->executeInternal(Array, Array, false)
#15 .../vendor/danack/auryn/lib/Provider.php(36): Auryn\AurynInjector->execute(Array, Array, false)
#16 .../bin/cli(106): Auryn\Provider->execute(Array, Array)
#17 {main}

```

Versions being used are:
* amp: c21068fc946f5bfd692297e927773a732f205279
* artax: 3e4c07759064c39ca7a8f9c1b4c9742e9b5143fe

And running on OSX with the NativeReactor.

**Comment by douggr** [comment]
I ran into the same issue.

```sh
php danack-issue-71.php
# Got `Timeout exception`, as expected, I was downloading a 1GB file to test :)

php danack-issue-71.php
# Got `Unknown socket`
```

I tried setting a timeout to a lower value (like 500ms) and check if could
reproduce it once again, but no success.

artax: 1.0.0-rc6

Couldn't not reproduce in `artax@master`

**Comment by Danack** [comment]
i can now see this is a simple example:

```
git clone https://github.com/danack/GithubArtaxService
cd GithubArtaxService/
composer install
php test/manualTest.php
```

It seems to be linked to file size - small files don't show the problem, larger files do.
