### ISSUE TITLE
Cannot update resolved promise

### ISSUE THREAD

**Issue by charmpitz** [amphp/artax#75]
I have this nasty error and pisses me off.. This is the code i use:
```php
$body = (new FormBody)
    // ->addField('name', 'torrents')
    ->addFile('torrents', './torrents/Suits.S04E01.1080p.WEB-DL.DD5.1.H.264-NTb.torrent')
;

$request = (new Request)
    ->setUri('http://localhost:8080/command/upload')
    ->setMethod('POST')
    ->setBody($body)
;
try {
	$response = \Amp\wait((new Client)->request($request));
} catch (Amp\Artax\ClientException $e) {
    echo $e;
}
```
This is the error im getting:
```php
PHP Fatal error:  Uncaught exception 'LogicException' with message 'Cannot update resolved promise' in /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/amp/lib/Future.php:94
Stack trace:
#0 /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/artax/lib/Client.php(481): Amp\Future->update(Array)
#1 /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/artax/lib/Client.php(473): Amp\Artax\Client->parseSocketData(Object(Amp\Artax\RequestCycle))
#2 /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/artax/lib/Client.php(456): Amp\Artax\Client->consumeSocketData(Object(Amp\Artax\RequestCycle), 'HTTP/1.1 200 OK...')
#3 /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/artax/lib/Client.php(436): Amp\Artax\Client->onReadableSocket(Object(Amp\Artax\RequestCycle))
#4 /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/amp/lib/NativeReactor.php(178): Amp\Artax\Client->Amp\Artax\{closure}(Object(Amp\NativeReactor), 3, Resource id #80)
#5 /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/amp/li in /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/amp/lib/Future.php on line 94
```

**Comment by rdlowrey** [comment]
Thanks for the report. I suspect this is failing because the client is mishandling a redirect. Could you please post the output of the following code so I can get an idea of what's going on?

```php
function notifyCallback(array $notifyData) {
    switch ($notifyData[0]) {
        case Amp\Artax\Notify::SOCK_PROCURED:
            echo "SOCK_PROCURED\n";
            break;
        case Amp\Artax\Notify::SOCK_DATA_IN:
            echo "SOCK_DATA_IN\n";
            break;
        case Amp\Artax\Notify::SOCK_DATA_OUT:
            echo "SOCK_DATA_OUT\n";
            break;
        case Amp\Artax\Notify::REQUEST_SENT:
            echo "REQUEST_SENT\n";
            break;
        case Amp\Artax\Notify::RESPONSE_HEADERS:
            echo "RESPONSE_HEADERS\n", $notifyData[1]['trace'];
            break;
        case Amp\Artax\Notify::RESPONSE_BODY_DATA:
            echo "RESPONSE_BODY_DATA\n";
            break;
        case Amp\Artax\Notify::RESPONSE:
            echo "RESPONSE\n";
            break;
        case Amp\Artax\Notify::REDIRECT:
            echo "REDIRECT\n";
            break;
        case Amp\Artax\Notify::ERROR:
            echo "ERROR\n";
            break;
    }
}

$body = (new FormBody)
    // ->addField('name', 'torrents')
    ->addFile('torrents', './torrents/Suits.S04E01.1080p.WEB-DL.DD5.1.H.264-NTb.torrent')
;

$request = (new Request)
    ->setUri('http://localhost:8080/command/upload')
    ->setMethod('POST')
    ->setBody($body)
;
try {
    $promise = (new Client)->request($request);
    $promise->watch('notifyCallback');
    $response = \Amp\wait($promise);
} catch (Amp\Artax\ClientException $e) {
    echo $e;
}
```

**Comment by charmpitz** [comment]
```php
SOCK_PROCURED
SOCK_DATA_OUT
SOCK_DATA_OUT
SOCK_DATA_OUT
SOCK_DATA_OUT
SOCK_DATA_OUT
SOCK_DATA_OUT
REQUEST_SENT
SOCK_DATA_IN
RESPONSE_HEADERS
HTTP/1.1 200 OK
content-type: text/html
content-encoding: gzip
content-length: 76
RESPONSE_BODY_DATA
RESPONSE
PHP Fatal error:  Uncaught exception 'LogicException' with message 'Cannot update resolved promise' in /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/amp/lib/Future.php:94
Stack trace:
#0 /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/artax/lib/Client.php(481): Amp\Future->update(Array)
#1 /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/artax/lib/Client.php(473): Amp\Artax\Client->parseSocketData(Object(Amp\Artax\RequestCycle))
#2 /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/artax/lib/Client.php(456): Amp\Artax\Client->consumeSocketData(Object(Amp\Artax\RequestCycle), 'HTTP/1.1 200 OK...')
#3 /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/artax/lib/Client.php(436): Amp\Artax\Client->onReadableSocket(Object(Amp\Artax\RequestCycle))
#4 /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/amp/lib/NativeReactor.php(178): Amp\Artax\Client->Amp\Artax\{closure}(Object(Amp\NativeReactor), 3, Resource id #80)
#5 /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/amp/li in /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/amp/lib/Future.php on line 94
```

**Comment by rdlowrey** [comment]
Hmm. Thanks ... guess it's not a redirect problem. Will work on it this weekend.

**Comment by charmpitz** [comment]
Thank you :)

**Comment by rdlowrey** [comment]
@charmpitz I just pushed a commit that I think will fix the issue (it's difficult to know for sure without a reproduce case I can test myself). Can you let me know if the current master branch solves the problem for you?

**Comment by charmpitz** [comment]
Thanks but still doesn't work, i get the following:
```php
SOCK_PROCURED
ERROR
exception 'Amp\Artax\SocketException' with message 'Connection to server severed before the request write could complete.' in /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/artax/lib/BufferWriter.php:45
Stack trace:
#0 /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/artax/lib/BufferWriter.php(30): Amp\Artax\BufferWriter->doWrite()
#1 /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/amp/lib/NativeReactor.php(122): Amp\Artax\BufferWriter->Amp\Artax\{closure}(Object(Amp\NativeReactor), 5)
#2 /media/ady/Storage_Drive/Dropbox/www/tripper/vendor/amphp/amp/lib/functions.php(546): Amp\NativeReactor->tick()
#3 /media/ady/Storage_Drive/Dropbox/www/tripper/go.php(121): Amp\wait(Object(Amp\Future))
```
